% Load spanwise station data generated by Python.
% Run from the repository root in MATLAB.

stations = readtable('outputs/matlab/spanwise_stations.csv');

disp('Loaded spanwise stations:');
disp(stations(1:min(5,height(stations)), :));

% Useful variables for later CLT/beam modules:
y = stations.y_m;
chord = stations.chord_m;
twist_deg = stations.twist_deg;
x_ea = stations.x_ea_m;
x_ac = stations.x_ac_m;
e_ac_ea = stations.x_ac_minus_x_ea_m;
